server:
  port: 8081

spring:
  task:
    execution:
      pool:
        core-size: 8
        max-size: 8
      thread-name-prefix: "executor-v2-"
  datasource:
    url: jdbc:h2:tcp://localhost/~/seul-db-test
    username: sa
    password:
    driver-class-name: org.h2.Driver